// Women-specific beauty catalog — chunk 3 of 4
// Categories: kbeauty_inspired … gardener_beauty (contiguous slice of the
// original 3,359-line catalog; merge order in womensServicesData.ts
// preserves the categories endpoint order).
export const womensCatalog3 = {
  kbeauty_inspired: {
    nameAr: 'جمال كوري',
    nameEn: 'K-Beauty Inspired',
    emoji: '',
    description: 'إطلالات مستوحاة من الجمال الكوري — نضارة وإشراقة',
    subServices: [
      {
        id: 'kb1',
        nameAr: 'روتين كوري',
        nameEn: 'K-Beauty Routine',
        price: 280,
        durationMin: 60,
        emoji: '',
        precautions: '١٠ خطوات للعناية',
      },
      {
        id: 'kb2',
        nameAr: 'مكياج كوري',
        nameEn: 'K-Beauty Makeup',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'إطلالة طبيعية ناعمة',
      },
      {
        id: 'kb3',
        nameAr: 'قناع وجه كوري',
        nameEn: 'Korean Sheet Mask',
        price: 100,
        durationMin: 20,
        emoji: '',
        precautions: 'ورق كوري أصلي',
      },
    ],
  },
  eco_beauty: {
    nameAr: 'الجمال المستدام',
    nameEn: 'Eco-Conscious Beauty',
    emoji: '',
    description: 'خدمات تجميل صديقة للبيئة — جميلة أنتِ وجميلة الأرض',
    subServices: [
      {
        id: 'ec1',
        nameAr: 'عناية بشرة صديقة للبيئة',
        nameEn: 'Eco-Friendly Facial',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'منتجات قابلة للتحلل',
      },
      {
        id: 'ec2',
        nameAr: 'صبغات نباتية',
        nameEn: 'Plant-Based Hair Color',
        price: 300,
        durationMin: 90,
        emoji: '',
        precautions: 'خالي من الأمونيا',
      },
      {
        id: 'ec3',
        nameAr: 'باقة خضراء',
        nameEn: 'Green Package',
        price: 450,
        durationMin: 120,
        emoji: '️',
        precautions: 'بصمة كربونية منخفضة',
      },
    ],
  },
  volunteer_beauty: {
    nameAr: 'عناية المتطوعات',
    nameEn: 'Volunteer Woman Beauty',
    emoji: '',
    description: 'خدمات مخصصة للمتطوعات — شكراً لعطائكِ',
    subServices: [
      {
        id: 'vl1',
        nameAr: 'باقة المتطوعة',
        nameEn: 'Volunteer Package',
        price: 200,
        durationMin: 75,
        emoji: '',
        precautions: 'خصم خاص للمتطوعات',
      },
      {
        id: 'vl2',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Relaxation Session',
        price: 150,
        durationMin: 45,
        emoji: '‍️',
        precautions: 'بعد يوم تطوعي',
      },
      {
        id: 'vl3',
        nameAr: 'إطلالة مناسبة خيرية',
        nameEn: 'Charity Event Look',
        price: 180,
        durationMin: 50,
        emoji: '️',
        precautions: 'لحضور الفعاليات',
      },
    ],
  },
  gamer_beauty: {
    nameAr: 'عناية اللاعبات',
    nameEn: 'Gamer Girl Beauty',
    emoji: '',
    description: 'خدمات تجميل لمحبات الألعاب — إطلالات مستوحاة من عالم الألعاب',
    subServices: [
      {
        id: 'gm1',
        nameAr: 'مانيكير ألعاب',
        nameEn: 'Gamer Nail Art',
        price: 180,
        durationMin: 40,
        emoji: '',
        precautions: 'تصاميم شخصيات الألعاب',
      },
      {
        id: 'gm2',
        nameAr: 'عناية بالعينين',
        nameEn: 'Gamer Eye Care',
        price: 150,
        durationMin: 30,
        emoji: '️',
        precautions: 'لتخفيف إجهاد الشاشة',
      },
      {
        id: 'gm3',
        nameAr: 'إطلالة بطولة',
        nameEn: 'Tournament Look',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'للظهور في البطولات',
      },
    ],
  },
  writer_beauty: {
    nameAr: 'عناية الكاتبات',
    nameEn: 'Writer Woman Beauty',
    emoji: '️',
    description: 'خدمات تجميل للكاتبات والمؤلفات — لأن الكلمات الجميلة تبدأ من روح جميلة',
    subServices: [
      {
        id: 'wr1',
        nameAr: 'جلسة كتابة',
        nameEn: 'Writing Session',
        price: 200,
        durationMin: 60,
        emoji: '',
        precautions: 'مساج + وقت كتابة',
      },
      {
        id: 'wr2',
        nameAr: 'إطلالة توقيع كتاب',
        nameEn: 'Book Signing Look',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'إطلالة أدبية راقية',
      },
      {
        id: 'wr3',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Writer Hand Care',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'للأيدي المتعبة من الكتابة',
      },
    ],
  },
  photographer_beauty: {
    nameAr: 'عناية المصورات',
    nameEn: 'Photographer Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للمصورات — لأنكِ خلف الكاميرا تستحقين الظهور',
    subServices: [
      {
        id: 'ph1',
        nameAr: 'إطلالة أمام الكاميرا',
        nameEn: 'Behind-the-Lens Look',
        price: 280,
        durationMin: 55,
        emoji: '',
        precautions: 'للمناسبات الخاصة',
      },
      {
        id: 'ph2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Photographer Hand Care',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'للأيدي الحاملة للكاميرا',
      },
      {
        id: 'ph3',
        nameAr: 'مساج أكتاف',
        nameEn: 'Shoulder Massage',
        price: 200,
        durationMin: 35,
        emoji: '‍️',
        precautions: 'لتخفيف حمل المعدات',
      },
    ],
  },
  chef_beauty: {
    nameAr: 'عناية الطباخات',
    nameEn: 'Chef Woman Beauty',
    emoji: '‍',
    description: 'خدمات تجميل للطباخات والشيفات — لأن المطبخ والجمال يلتقيان',
    subServices: [
      {
        id: 'ch1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Chef Hand Care',
        price: 180,
        durationMin: 35,
        emoji: '',
        precautions: 'ترطيب مكثف',
      },
      {
        id: 'ch2',
        nameAr: 'عناية بشرة مقاومة للحرارة',
        nameEn: 'Heat-Resistant Facial',
        price: 220,
        durationMin: 45,
        emoji: '',
        precautions: 'للبشرة المعرضة للحرارة',
      },
      {
        id: 'ch3',
        nameAr: 'إطلالة مطعم',
        nameEn: 'Restaurant Look',
        price: 250,
        durationMin: 50,
        emoji: '️',
        precautions: 'للظهور في المطعم',
      },
    ],
  },
  dancer_beauty: {
    nameAr: 'عناية الراقصات',
    nameEn: 'Dancer Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للراقصات — مرونة وجمال في كل حركة',
    subServices: [
      {
        id: 'dn1',
        nameAr: 'مساج مرونة',
        nameEn: 'Flexibility Massage',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'زيوت دافئة',
      },
      {
        id: 'dn2',
        nameAr: 'إطلالة عرض',
        nameEn: 'Performance Look',
        price: 350,
        durationMin: 70,
        emoji: '',
        precautions: 'مكياج يدوم طويلاً',
      },
      {
        id: 'dn3',
        nameAr: 'عناية بالأقدام',
        nameEn: 'Dancer Foot Care',
        price: 200,
        durationMin: 40,
        emoji: '',
        precautions: 'للأقدام المتعبة',
      },
    ],
  },
  designer_beauty: {
    nameAr: 'عناية المصممات',
    nameEn: 'Fashion Designer Beauty',
    emoji: '',
    description: 'خدمات تجميل لمصممات الأزياء — لأن الأناقة تبدأ منكِ',
    subServices: [
      {
        id: 'ds1',
        nameAr: 'إطلالة عرض أزياء',
        nameEn: 'Fashion Show Look',
        price: 400,
        durationMin: 80,
        emoji: '',
        precautions: 'إطلالة راقية',
      },
      {
        id: 'ds2',
        nameAr: 'استشارة ألوان',
        nameEn: 'Color Consultation',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'تحليل ألوان البشرة',
      },
      {
        id: 'ds3',
        nameAr: 'باقة المصممة',
        nameEn: 'Designer Package',
        price: 600,
        durationMin: 150,
        emoji: '',
        precautions: 'شعر + مكياج + أظافر',
      },
    ],
  },
  florist_beauty: {
    nameAr: 'عناية بائعات الزهور',
    nameEn: 'Florist Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل لمحبات وبائعات الزهور — جمال الطبيعة في عنايتكِ',
    subServices: [
      {
        id: 'fl1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Florist Hand Care',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'ترميم الأيدي المتعبة',
      },
      {
        id: 'fl2',
        nameAr: 'باقة ورود وعناية',
        nameEn: 'Flowers & Facial',
        price: 350,
        durationMin: 90,
        emoji: '',
        precautions: 'باقة ورد + عناية بالبشرة',
      },
      {
        id: 'fl3',
        nameAr: 'إطلالة محل',
        nameEn: 'Shop Look',
        price: 200,
        durationMin: 45,
        emoji: '',
        precautions: 'إطلالة منعشة',
      },
    ],
  },
  interpreter_beauty: {
    nameAr: 'عناية المترجمات',
    nameEn: 'Interpreter Woman Beauty',
    emoji: '️',
    description: 'خدمات عناية للمترجمات — لأن صوتكِ الجميل يستحق إطلالة أجمل',
    subServices: [
      {
        id: 'it1',
        nameAr: 'عناية بالصوت',
        nameEn: 'Voice Care',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'مساج حنجرة وأعشاب',
      },
      {
        id: 'it2',
        nameAr: 'إطلالة مؤتمر',
        nameEn: 'Conference Look',
        price: 300,
        durationMin: 60,
        emoji: '️',
        precautions: 'احترافية وأنيقة',
      },
      {
        id: 'it3',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Interpreter Relaxation',
        price: 220,
        durationMin: 50,
        emoji: '‍️',
        precautions: 'لتخفيف ضغط العمل',
      },
    ],
  },
  musician_beauty: {
    nameAr: 'عناية الموسيقيات',
    nameEn: 'Musician Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للموسيقيات — لأن الموسيقى والجمال لحن واحد',
    subServices: [
      {
        id: 'mu1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Musician Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'للعازفات على الآلات',
      },
      {
        id: 'mu2',
        nameAr: 'إطلالة حفل',
        nameEn: 'Concert Look',
        price: 350,
        durationMin: 70,
        emoji: '',
        precautions: 'مكياج + شعر',
      },
      {
        id: 'mu3',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Musician Relaxation',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'بعد البروفات',
      },
    ],
  },
  actress_beauty: {
    nameAr: 'عناية الممثلات',
    nameEn: 'Actress Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للممثلات — من خشبة المسرح للشاشة',
    subServices: [
      {
        id: 'ac1',
        nameAr: 'مكياج مسرحي',
        nameEn: 'Stage Makeup',
        price: 400,
        durationMin: 75,
        emoji: '',
        precautions: 'يدوم تحت الأضواء',
      },
      {
        id: 'ac2',
        nameAr: 'إطلالة بريمير',
        nameEn: 'Premiere Look',
        price: 500,
        durationMin: 90,
        emoji: '',
        precautions: 'إطلالة السجادة الحمراء',
      },
      {
        id: 'ac3',
        nameAr: 'عناية بالبشرة',
        nameEn: 'Actor Skincare',
        price: 280,
        durationMin: 50,
        emoji: '',
        precautions: 'للبشرة بعد المكياج الثقيل',
      },
    ],
  },
  architect_beauty: {
    nameAr: 'عناية المعماريات',
    nameEn: 'Architect Woman Beauty',
    emoji: '️',
    description: 'خدمات تجميل للمعماريات — لأنكِ تصممين الجمال حولكِ',
    subServices: [
      {
        id: 'ah1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Architect Hand Care',
        price: 180,
        durationMin: 30,
        emoji: '',
        precautions: 'للأيدي العاملة على المخططات',
      },
      {
        id: 'ah2',
        nameAr: 'إطلالة عرض مشروع',
        nameEn: 'Project Pitch Look',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'احترافية وواثقة',
      },
      {
        id: 'ah3',
        nameAr: 'مساج ظهر',
        nameEn: 'Back Massage',
        price: 250,
        durationMin: 45,
        emoji: '‍️',
        precautions: 'لتخفيف آلام الجلوس',
      },
    ],
  },
  pilot_beauty: {
    nameAr: 'عناية الطيارات',
    nameEn: 'Pilot Woman Beauty',
    emoji: '️',
    description: 'خدمات تجميل للطيارات والمضيفات — الجمال في الأجواء',
    subServices: [
      {
        id: 'pl1',
        nameAr: 'عناية مرطبة',
        nameEn: 'Hydration Facial',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'لبشرة الطائرة الجافة',
      },
      {
        id: 'pl2',
        nameAr: 'إطلالة طيران',
        nameEn: 'Flight Ready Look',
        price: 200,
        durationMin: 40,
        emoji: '',
        precautions: 'يدوم طوال الرحلة',
      },
      {
        id: 'pl3',
        nameAr: 'استرخاء ترانزيت',
        nameEn: 'Transit Relaxation',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'بين الرحلات',
      },
    ],
  },
  farmer_beauty: {
    nameAr: 'عناية المزارعات',
    nameEn: 'Farmer Woman Beauty',
    emoji: '‍',
    description: 'خدمات تجميل للمرأة العاملة في الأرض — جمال الطبيعة',
    subServices: [
      {
        id: 'fm1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Farmer Hand Care',
        price: 180,
        durationMin: 35,
        emoji: '',
        precautions: 'ترميم وترطيب عميق',
      },
      {
        id: 'fm2',
        nameAr: 'عناية بشرة طبيعية',
        nameEn: 'Natural Facial',
        price: 200,
        durationMin: 45,
        emoji: '',
        precautions: 'منتجات من الطبيعة',
      },
      {
        id: 'fm3',
        nameAr: 'مساج ظهر',
        nameEn: 'Back Massage',
        price: 250,
        durationMin: 50,
        emoji: '‍️',
        precautions: 'لتخفيف آلام العمل',
      },
    ],
  },
  librarian_beauty: {
    nameAr: 'عناية أمينات المكتبات',
    nameEn: 'Librarian Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل لأمينات المكتبات — أناقة المعرفة',
    subServices: [
      {
        id: 'lb1',
        nameAr: 'إطلالة هادئة',
        nameEn: 'Quiet Elegance Look',
        price: 200,
        durationMin: 45,
        emoji: '',
        precautions: 'مكياج ناعم',
      },
      {
        id: 'lb2',
        nameAr: 'جلسة قراءة',
        nameEn: 'Reading Relaxation',
        price: 300,
        durationMin: 80,
        emoji: '',
        precautions: 'مساج + كتاب + شاي',
      },
      {
        id: 'lb3',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Librarian Hand Care',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'للأيدي المتعاملة مع الكتب',
      },
    ],
  },
  sailor_beauty: {
    nameAr: 'عناية البحريات',
    nameEn: 'Sailor Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للعاملات في البحر — جمال يقاوم الملوحة',
    subServices: [
      {
        id: 'sb1',
        nameAr: 'عناية مقاومة للملوحة',
        nameEn: 'Salt-Resistant Facial',
        price: 280,
        durationMin: 50,
        emoji: '',
        precautions: 'حماية من海水',
      },
      {
        id: 'sb2',
        nameAr: 'عناية بالشعر',
        nameEn: 'Marine Hair Care',
        price: 250,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'ترميم من أضرار الملوحة',
      },
      {
        id: 'sb3',
        nameAr: 'مساج بحري',
        nameEn: 'Marine Massage',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'بأملاح البحر الميت',
      },
    ],
  },
  veterinarian_beauty: {
    nameAr: 'عناية الطبيبات البيطريات',
    nameEn: 'Veterinarian Beauty',
    emoji: '',
    description: 'خدمات تجميل للطبيبات البيطريات — لأنكِ تعتنين بالجميع إلا نفسكِ',
    subServices: [
      {
        id: 'vt1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Vet Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'تعقيم وترميم',
      },
      {
        id: 'vt2',
        nameAr: 'مساج ظهر',
        nameEn: 'Back Recovery Massage',
        price: 280,
        durationMin: 50,
        emoji: '‍️',
        precautions: 'لتخفيف آلام الانحناء',
      },
      {
        id: 'vt3',
        nameAr: 'باقة الطبيبة',
        nameEn: 'Veterinarian Package',
        price: 400,
        durationMin: 100,
        emoji: '',
        precautions: 'مساج + بشرة + أظافر',
      },
    ],
  },
  pharmacist_beauty: {
    nameAr: 'عناية الصيدلانيات',
    nameEn: 'Pharmacist Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للصيدلانيات — أنتِ خبيرة التركيبات',
    subServices: [
      {
        id: 'ph1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Pharmacist Hand Care',
        price: 180,
        durationMin: 30,
        emoji: '',
        precautions: 'ترميم من جفاف المعقمات',
      },
      {
        id: 'ph2',
        nameAr: 'إطلالة صيدلية',
        nameEn: 'Pharmacy Look',
        price: 200,
        durationMin: 45,
        emoji: '',
        precautions: 'مكياج خفيف وطبيعي',
      },
      {
        id: 'ph3',
        nameAr: 'استرخاء بعد الدوام',
        nameEn: 'Post-Shift Relaxation',
        price: 250,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'بعد وقوف طويل',
      },
    ],
  },
  dentist_beauty: {
    nameAr: 'عناية طبيبات الأسنان',
    nameEn: 'Dentist Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل لطبيبات الأسنان — ابتسامة جميلة تستحقينها',
    subServices: [
      {
        id: 'dt1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Dentist Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'للأيدي الدقيقة',
      },
      {
        id: 'dt2',
        nameAr: 'مساج رقبة وأكتاف',
        nameEn: 'Neck & Shoulder Massage',
        price: 250,
        durationMin: 45,
        emoji: '‍️',
        precautions: 'لتخفيف آلام الانحناء',
      },
      {
        id: 'dt3',
        nameAr: 'إطلالة عيادة',
        nameEn: 'Clinic Look',
        price: 280,
        durationMin: 55,
        emoji: '',
        precautions: 'احترافية وأنيقة',
      },
    ],
  },
  psychologist_beauty: {
    nameAr: 'عناية المعالجات النفسيات',
    nameEn: 'Psychologist Woman Beauty',
    emoji: '',
    description: 'خدمات عناية للمعالجات النفسيات — لأنكِ تستمعين للجميع، استمعي لجسدكِ',
    subServices: [
      {
        id: 'py1',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Deep Relaxation',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'لتفريغ الطاقة',
      },
      {
        id: 'py2',
        nameAr: 'مساج تأملي',
        nameEn: 'Meditation Massage',
        price: 350,
        durationMin: 75,
        emoji: '️',
        precautions: 'زيوت مهدئة',
      },
      {
        id: 'py3',
        nameAr: 'إطلالة عيادة',
        nameEn: 'Practice Look',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'مريحة واحترافية',
      },
    ],
  },
  dietitian_beauty: {
    nameAr: 'عناية أخصائيات التغذية',
    nameEn: 'Dietitian Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل لأخصائيات التغذية — جمال من الداخل والخارج',
    subServices: [
      {
        id: 'di1',
        nameAr: 'عناية بشرة مغذية',
        nameEn: 'Nourishing Facial',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'مكونات طبيعية',
      },
      {
        id: 'di2',
        nameAr: 'باقة الصحة والجمال',
        nameEn: 'Health & Beauty Package',
        price: 400,
        durationMin: 100,
        emoji: '',
        precautions: 'عناية + استشارة غذائية',
      },
      {
        id: 'di3',
        nameAr: 'إطلالة عيادة',
        nameEn: 'Clinic Consultation Look',
        price: 200,
        durationMin: 45,
        emoji: '',
        precautions: 'طبيعي ومنعش',
      },
    ],
  },
  social_worker_beauty: {
    nameAr: 'عناية الأخصائيات الاجتماعيات',
    nameEn: 'Social Worker Beauty',
    emoji: '',
    description: 'خدمات عناية للأخصائيات الاجتماعيات — لأنكِ تقدمين للآخرين كل يوم',
    subServices: [
      {
        id: 'sw1',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Social Worker Relaxation',
        price: 220,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'لتخفيف الضغط',
      },
      {
        id: 'sw2',
        nameAr: 'باقة العطاء',
        nameEn: 'Giver Package',
        price: 350,
        durationMin: 100,
        emoji: '',
        precautions: 'خصم خاص',
      },
      {
        id: 'sw3',
        nameAr: 'إطلالة ميدانية',
        nameEn: 'Field Visit Look',
        price: 180,
        durationMin: 40,
        emoji: '️',
        precautions: 'عملية ومريحة',
      },
    ],
  },
  physiotherapist_beauty: {
    nameAr: 'عناية المعالجات الطبيعيات',
    nameEn: 'Physiotherapist Beauty',
    emoji: '',
    description: 'خدمات تجميل للمعالجات الطبيعيات — لأنكِ تعالجين الأجسام، عالجي جسدكِ',
    subServices: [
      {
        id: 'pt1',
        nameAr: 'مساج عضلي',
        nameEn: 'Deep Tissue Massage',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'لتخفيف إجهاد العضلات',
      },
      {
        id: 'pt2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Therapist Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'للأيدي القوية',
      },
      {
        id: 'pt3',
        nameAr: 'باقة المعالجة',
        nameEn: 'Therapist Package',
        price: 450,
        durationMin: 120,
        emoji: '️‍️',
        precautions: 'مساج + بشرة + أظافر',
      },
    ],
  },
  gardener_beauty: {
    nameAr: 'عناية البستانيات',
    nameEn: 'Gardener Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل لمحبات الزراعة والبستنة — جمال الطبيعة في يديكِ',
    subServices: [
      {
        id: 'gd1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Gardener Hand Care',
        price: 180,
        durationMin: 35,
        emoji: '',
        precautions: 'ترميم وترطيب عميق',
      },
      {
        id: 'gd2',
        nameAr: 'باقة الطبيعة',
        nameEn: 'Nature Package',
        price: 300,
        durationMin: 90,
        emoji: '',
        precautions: 'بشرة + شعر بمنتجات نباتية',
      },
      {
        id: 'gd3',
        nameAr: 'إطلالة حديقة',
        nameEn: 'Garden Party Look',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'إطلالة منعشة وطبيعية',
      },
    ],
  },
};
