// Women-specific beauty catalog — chunk 4 of 4
// Categories: yoga_instructor … influencer_beauty (contiguous slice of the
// original 3,359-line catalog; merge order in womensServicesData.ts
// preserves the categories endpoint order).
export const womensCatalog4 = {
  yoga_instructor: {
    nameAr: 'عناية مدربات اليوغا',
    nameEn: 'Yoga Instructor Beauty',
    emoji: '‍️',
    description: 'خدمات تجميل لمدربات اليوغا — توازن الجسد والروح',
    subServices: [
      {
        id: 'yg1',
        nameAr: 'مساج مرونة',
        nameEn: 'Flexibility Massage',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'زيوت أيورفيدا',
      },
      {
        id: 'yg2',
        nameAr: 'إطلالة zen',
        nameEn: 'Zen Look',
        price: 200,
        durationMin: 40,
        emoji: '️',
        precautions: 'مكياج طبيعي جداً',
      },
      {
        id: 'yg3',
        nameAr: 'جلسة تأمل',
        nameEn: 'Meditation Session',
        price: 350,
        durationMin: 90,
        emoji: '️',
        precautions: 'مساج + تأمل + شاي',
      },
    ],
  },
  horse_rider: {
    nameAr: 'عناية الفارسات',
    nameEn: 'Horse Rider Beauty',
    emoji: '',
    description: 'خدمات تجميل للفارسات وراكبات الخيل',
    subServices: [
      {
        id: 'hr1',
        nameAr: 'مساج ظهر',
        nameEn: 'Rider Back Massage',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'لتخفيف آلام الركوب',
      },
      {
        id: 'hr2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Rider Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'لليدين بعد اللجام',
      },
      {
        id: 'hr3',
        nameAr: 'إطلالة سباق',
        nameEn: 'Race Day Look',
        price: 350,
        durationMin: 60,
        emoji: '',
        precautions: 'لأيام السباقات',
      },
    ],
  },
  swimmer_beauty: {
    nameAr: 'عناية السباحات',
    nameEn: 'Swimmer Woman Beauty',
    emoji: '‍️',
    description: 'خدمات تجميل للسباحات — جمال يقاوم الكلور',
    subServices: [
      {
        id: 'sw1',
        nameAr: 'عناية مقاومة للكلور',
        nameEn: 'Chlorine-Resistant Facial',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'حماية من الكلور',
      },
      {
        id: 'sw2',
        nameAr: 'عناية بالشعر',
        nameEn: 'Swimmer Hair Care',
        price: 280,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'ترميم من الكلور',
      },
      {
        id: 'sw3',
        nameAr: 'مساج عضلي',
        nameEn: 'Swimmer Muscle Massage',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'استرخاء العضلات',
      },
    ],
  },
  boxer_beauty: {
    nameAr: 'عناية الملاكمات',
    nameEn: 'Boxer Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للملاكمات — قوة وجمال',
    subServices: [
      {
        id: 'bx1',
        nameAr: 'مساج عضلي',
        nameEn: 'Deep Recovery Massage',
        price: 350,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'استرخاء عميق',
      },
      {
        id: 'bx2',
        nameAr: 'عناية بالوجه',
        nameEn: 'Post-Training Facial',
        price: 280,
        durationMin: 50,
        emoji: '',
        precautions: 'تهدئة البشرة',
      },
      {
        id: 'bx3',
        nameAr: 'إطلالة نزال',
        nameEn: 'Fight Night Look',
        price: 300,
        durationMin: 55,
        emoji: '️',
        precautions: 'للظهور الإعلامي',
      },
    ],
  },
  runner_beauty: {
    nameAr: 'عناية العداءات',
    nameEn: 'Runner Woman Beauty',
    emoji: '‍️',
    description: 'خدمات تجميل للعداءات — جمال في الحركة',
    subServices: [
      {
        id: 'rn1',
        nameAr: 'عناية بالأقدام',
        nameEn: 'Runner Foot Care',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'لأقدام العداءات',
      },
      {
        id: 'rn2',
        nameAr: 'مساج عضلي',
        nameEn: 'Runner Muscle Massage',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'استرخاء بعد الماراثون',
      },
      {
        id: 'rn3',
        nameAr: 'إطلالة سباق',
        nameEn: 'Race Day Look',
        price: 200,
        durationMin: 40,
        emoji: '',
        precautions: 'للظهور في السباقات',
      },
    ],
  },
  weightlifter_beauty: {
    nameAr: 'عناية رافعات الأثقال',
    nameEn: 'Weightlifter Beauty',
    emoji: '️‍️',
    description: 'خدمات تجميل لرافعات الأثقال — قوة وأنوثة',
    subServices: [
      {
        id: 'wl1',
        nameAr: 'مساج عضلي عميق',
        nameEn: 'Deep Muscle Recovery',
        price: 350,
        durationMin: 60,
        emoji: '',
        precautions: 'استرخاء العضلات',
      },
      {
        id: 'wl2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Lifter Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'ترميم الأيدي',
      },
      {
        id: 'wl3',
        nameAr: 'إطلالة بطولة',
        nameEn: 'Competition Look',
        price: 300,
        durationMin: 55,
        emoji: '',
        precautions: 'للظهور في البطولات',
      },
    ],
  },
  cyclist_beauty: {
    nameAr: 'عناية الدراجات',
    nameEn: 'Cyclist Woman Beauty',
    emoji: '‍️',
    description: 'خدمات تجميل لراكبات الدراجات — جمال على الطريق',
    subServices: [
      {
        id: 'cy1',
        nameAr: 'مساج أرجل',
        nameEn: 'Leg Recovery Massage',
        price: 300,
        durationMin: 55,
        emoji: '',
        precautions: 'استرخاء بعد الدراجة',
      },
      {
        id: 'cy2',
        nameAr: 'عناية بشرة مقاومة',
        nameEn: 'Wind-Resistant Facial',
        price: 250,
        durationMin: 45,
        emoji: '️',
        precautions: 'حماية من الرياح',
      },
      {
        id: 'cy3',
        nameAr: 'إطلالة سباق',
        nameEn: 'Race Look',
        price: 200,
        durationMin: 40,
        emoji: '',
        precautions: 'للظهور في السباقات',
      },
    ],
  },
  climber_beauty: {
    nameAr: 'عناية المتسلقات',
    nameEn: 'Climber Woman Beauty',
    emoji: '‍️',
    description: 'خدمات تجميل لمتسلقات الجبال — جمال القمم',
    subServices: [
      {
        id: 'cl1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Climber Hand Care',
        price: 220,
        durationMin: 40,
        emoji: '',
        precautions: 'ترميم عميق',
      },
      {
        id: 'cl2',
        nameAr: 'مساج عضلي',
        nameEn: 'Full Body Recovery',
        price: 350,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'استرخاء كامل',
      },
      {
        id: 'cl3',
        nameAr: 'إطلالة قمة',
        nameEn: 'Summit Look',
        price: 250,
        durationMin: 45,
        emoji: '️',
        precautions: 'للاحتفال بالقمة',
      },
    ],
  },
  lawyer_beauty: {
    nameAr: 'عناية المحاميات',
    nameEn: 'Lawyer Woman Beauty',
    emoji: '️',
    description: 'إطلالات قوية للمحاميات — ثقة أمام القاضي',
    subServices: [
      {
        id: 'lw1',
        nameAr: 'إطلالة محكمة',
        nameEn: 'Courtroom Look',
        price: 350,
        durationMin: 65,
        emoji: '️',
        precautions: 'احترافية ورسمية',
      },
      {
        id: 'lw2',
        nameAr: 'إطلالة اجتماع',
        nameEn: 'Client Meeting Look',
        price: 280,
        durationMin: 50,
        emoji: '',
        precautions: 'ثقة واحترافية',
      },
      {
        id: 'lw3',
        nameAr: 'استرخاء بعد القضية',
        nameEn: 'Post-Case Relaxation',
        price: 350,
        durationMin: 80,
        emoji: '‍️',
        precautions: 'لتخفيف التوتر',
      },
    ],
  },
  banker_beauty: {
    nameAr: 'عناية المصرفيات',
    nameEn: 'Banker Woman Beauty',
    emoji: '',
    description: 'إطلالات أنيقة للمصرفيات — ثقة في كل معاملة',
    subServices: [
      {
        id: 'bk1',
        nameAr: 'إطلالة بنكية',
        nameEn: 'Banking Look',
        price: 300,
        durationMin: 55,
        emoji: '',
        precautions: 'أنيقة ومحترفة',
      },
      {
        id: 'bk2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Banker Hand Care',
        price: 200,
        durationMin: 30,
        emoji: '',
        precautions: 'أظافر أنيقة',
      },
      {
        id: 'bk3',
        nameAr: 'استرخاء بعد الدوام',
        nameEn: 'Post-Shift Relax',
        price: 280,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'لتخفيف الضغط',
      },
    ],
  },
  wedding_planner: {
    nameAr: 'عناية منظمات الحفلات',
    nameEn: 'Wedding Planner Beauty',
    emoji: '',
    description: 'خدمات تجميل لمنظمات الأفراح — أنتِ وراء كل زفاف جميل',
    subServices: [
      {
        id: 'wp1',
        nameAr: 'إطلالة يوم الزفاف',
        nameEn: 'Wedding Day Look',
        price: 350,
        durationMin: 60,
        emoji: '',
        precautions: 'للظهور يوم الزفاف',
      },
      {
        id: 'wp2',
        nameAr: 'مساج ظهر',
        nameEn: 'Back Recovery',
        price: 300,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'بعد يوم طويل',
      },
      {
        id: 'wp3',
        nameAr: 'باقة المنظمة',
        nameEn: 'Planner Package',
        price: 500,
        durationMin: 120,
        emoji: '',
        precautions: 'شعر + مكياج + استرخاء',
      },
    ],
  },
  call_center_beauty: {
    nameAr: 'عناية موظفات الاتصالات',
    nameEn: 'Call Center Beauty',
    emoji: '',
    description: 'خدمات عناية لموظفات خدمة العملاء — صوت جميل وإطلالة أجمل',
    subServices: [
      {
        id: 'cc1',
        nameAr: 'عناية بالصوت',
        nameEn: 'Voice Care Treatment',
        price: 150,
        durationMin: 30,
        emoji: '️',
        precautions: 'أعشاب ومرطبات',
      },
      {
        id: 'cc2',
        nameAr: 'مساج رقبة',
        nameEn: 'Neck & Head Massage',
        price: 220,
        durationMin: 40,
        emoji: '‍️',
        precautions: 'لتخفيف آلام السماعة',
      },
      {
        id: 'cc3',
        nameAr: 'استرخاء بعد المناوبة',
        nameEn: 'Post-Shift Relaxation',
        price: 250,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'لتفريغ ضغط المكالمات',
      },
    ],
  },
  real_estate_beauty: {
    nameAr: 'عناية العقاريات',
    nameEn: 'Real Estate Beauty',
    emoji: '️',
    description: 'إطلالات جاهزة للقاء العملاء — بيعي بأجمل إطلالة',
    subServices: [
      {
        id: 're1',
        nameAr: 'إطلالة عميلة',
        nameEn: 'Client Ready Look',
        price: 300,
        durationMin: 55,
        emoji: '',
        precautions: 'واثقة وجذابة',
      },
      {
        id: 're2',
        nameAr: 'إطلالة عرض عقاري',
        nameEn: 'Open House Look',
        price: 250,
        durationMin: 45,
        emoji: '',
        precautions: 'منعشة وطبيعية',
      },
      {
        id: 're3',
        nameAr: 'استرخاء بعد البيع',
        nameEn: 'Post-Sale Relax',
        price: 350,
        durationMin: 75,
        emoji: '',
        precautions: 'احتفال بالإنجاز',
      },
    ],
  },
  accountant_beauty: {
    nameAr: 'عناية المحاسبات',
    nameEn: 'Accountant Woman Beauty',
    emoji: '',
    description: 'خدمات عناية للمحاسبات — دقة وجمال في الأرقام',
    subServices: [
      {
        id: 'ac1',
        nameAr: 'مساج ظهر',
        nameEn: 'Back & Neck Massage',
        price: 280,
        durationMin: 50,
        emoji: '‍️',
        precautions: 'لتخفيف آلام الجلوس',
      },
      {
        id: 'ac2',
        nameAr: 'عناية بالعينين',
        nameEn: 'Screen-Time Eye Care',
        price: 200,
        durationMin: 30,
        emoji: '️',
        precautions: 'لتخفيف إجهاد الأرقام',
      },
      {
        id: 'ac3',
        nameAr: 'استرخاء موسم الضرائب',
        nameEn: 'Tax Season Relief',
        price: 400,
        durationMin: 100,
        emoji: '‍️',
        precautions: 'لتخفيف ضغط الموسم',
      },
    ],
  },
  event_host_beauty: {
    nameAr: 'عناية مقدمات الحفلات',
    nameEn: 'Event Host Beauty',
    emoji: '',
    description: 'إطلالات مبهرة لمقدمات الحفلات والمناسبات',
    subServices: [
      {
        id: 'eh1',
        nameAr: 'إطلالة مسرح',
        nameEn: 'Stage Look',
        price: 400,
        durationMin: 70,
        emoji: '',
        precautions: 'يدوم تحت الأضواء',
      },
      {
        id: 'eh2',
        nameAr: 'إطلالة حفل',
        nameEn: 'Event Look',
        price: 350,
        durationMin: 60,
        emoji: '',
        precautions: 'أنيقة وجذابة',
      },
      {
        id: 'eh3',
        nameAr: 'عناية بالصوت',
        nameEn: 'Voice Care',
        price: 180,
        durationMin: 30,
        emoji: '️',
        precautions: 'أعشاب ومرطبات للحنجرة',
      },
    ],
  },
  grandmother_bride: {
    nameAr: 'عناية الجدة العروس',
    nameEn: 'Grandmother Bride Beauty',
    emoji: '',
    description: 'عناية خاصة للجدات المتزوجات — الحب ليس له عمر',
    subServices: [
      {
        id: 'gb1',
        nameAr: 'إطلالة زفاف',
        nameEn: 'Wedding Look',
        price: 400,
        durationMin: 80,
        emoji: '',
        precautions: 'راقية ومناسبة للعمر',
      },
      {
        id: 'gb2',
        nameAr: 'باقة الجدة العروس',
        nameEn: 'Grandma Bride Package',
        price: 700,
        durationMin: 160,
        emoji: '',
        precautions: 'شعر + مكياج + أظافر',
      },
      {
        id: 'gb3',
        nameAr: 'عناية بالبشرة',
        nameEn: 'Bridal Skincare',
        price: 300,
        durationMin: 55,
        emoji: '',
        precautions: 'ترطيب مكثف',
      },
    ],
  },
  twins_mom: {
    nameAr: 'عناية أم التوائم',
    nameEn: 'Twins Mother Beauty',
    emoji: '',
    description: 'خدمات سريعة لأمهات التوائم — لأن وقتكِ ثمين',
    subServices: [
      {
        id: 'tm1',
        nameAr: 'باقة سريعة',
        nameEn: 'Express Package',
        price: 350,
        durationMin: 60,
        emoji: '',
        precautions: '٣ خدمات في ساعة',
      },
      {
        id: 'tm2',
        nameAr: 'خدمة منزلية',
        nameEn: 'Home Visit',
        price: 500,
        durationMin: 120,
        emoji: '',
        precautions: 'الفنية تأتي إليكِ',
      },
      {
        id: 'tm3',
        nameAr: 'استرخاء الأمومة',
        nameEn: 'Motherhood Relaxation',
        price: 280,
        durationMin: 50,
        emoji: '‍️',
        precautions: 'استراحة تستحقينها',
      },
    ],
  },
  makeup_artist_self: {
    nameAr: 'عناية خبيرات التجميل',
    nameEn: 'MUA Self-Care',
    emoji: '',
    description: 'خدمات عناية لخبيرات التجميل أنفسهن — لأنكِ تستحقين العناية أيضاً',
    subServices: [
      {
        id: 'ma1',
        nameAr: 'عناية بالأيدي',
        nameEn: 'MUA Hand Care',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'للأيدي المبدعة',
      },
      {
        id: 'ma2',
        nameAr: 'مساج ظهر',
        nameEn: 'Back Recovery',
        price: 300,
        durationMin: 55,
        emoji: '‍️',
        precautions: 'بعد يوم طويل من العمل',
      },
      {
        id: 'ma3',
        nameAr: 'باقة الخبيرة',
        nameEn: 'MUA Package',
        price: 400,
        durationMin: 100,
        emoji: '',
        precautions: 'بشرة + شعر + أظافر',
      },
    ],
  },
  influencer_beauty: {
    nameAr: 'عناية المؤثرات',
    nameEn: 'Influencer Beauty',
    emoji: '',
    description: 'إطلالات جاهزة للتصوير — للمؤثرات وصانعات المحتوى',
    subServices: [
      {
        id: 'if1',
        nameAr: 'إطلالة تصوير',
        nameEn: 'Content Shoot Look',
        price: 350,
        durationMin: 65,
        emoji: '',
        precautions: 'يدوم تحت الإضاءة',
      },
      {
        id: 'if2',
        nameAr: 'إطلالة ستوري',
        nameEn: 'Story-Ready Look',
        price: 200,
        durationMin: 35,
        emoji: '',
        precautions: 'سريعة ومنعشة',
      },
      {
        id: 'if3',
        nameAr: 'باقة المحتوى',
        nameEn: 'Content Package',
        price: 600,
        durationMin: 150,
        emoji: '',
        precautions: '٣ إطلالات في جلسة',
      },
    ],
  },
};
