// Women-specific beauty catalog — chunk 2 of 4
// Categories: chronic_care … nomad_beauty (contiguous slice of the
// original 3,359-line catalog; merge order in womensServicesData.ts
// preserves the categories endpoint order).
export const womensCatalog2 = {
  chronic_care: {
    nameAr: 'عناية المريضات',
    nameEn: 'Chronic Illness Care',
    emoji: '',
    description: 'خدمات تجميل لطيفة للنساء المصابات بأمراض مزمنة — عناية برفق',
    subServices: [
      {
        id: 'cc1',
        nameAr: 'مساج لطيف',
        nameEn: 'Gentle Massage',
        price: 250,
        durationMin: 45,
        emoji: '',
        precautions: 'ضغط خفيف جداً',
      },
      {
        id: 'cc2',
        nameAr: 'عناية بشرة مهدئة',
        nameEn: 'Soothing Facial',
        price: 200,
        durationMin: 40,
        emoji: '',
        precautions: 'منتجات مضادة للحساسية',
      },
      {
        id: 'cc3',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Relaxation Session',
        price: 180,
        durationMin: 50,
        emoji: '‍️',
        precautions: 'بدون مجهود',
      },
    ],
  },
  plus_size_beauty: {
    nameAr: 'جمال المرأة الممتلئة',
    nameEn: 'Plus Size Beauty',
    emoji: '',
    description: 'خدمات تجميل شاملة للمرأة الممتلئة — كل جسم جميل',
    subServices: [
      {
        id: 'ps1',
        nameAr: 'مساج للجسم الممتلئ',
        nameEn: 'Plus Size Massage',
        price: 300,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'طاولة واسعة',
      },
      {
        id: 'ps2',
        nameAr: 'عناية بالبشرة',
        nameEn: 'Body-Positive Facial',
        price: 220,
        durationMin: 45,
        emoji: '',
        precautions: 'منتجات مناسبة',
      },
      {
        id: 'ps3',
        nameAr: 'تصفيف شعر',
        nameEn: 'Volumizing Styling',
        price: 200,
        durationMin: 45,
        emoji: '‍️',
        precautions: 'تسريحات تناسب الوجه',
      },
    ],
  },
  natural_beauty: {
    nameAr: 'الجمال الطبيعي',
    nameEn: 'Natural Beauty',
    emoji: '',
    description: 'خدمات تجميل ١٠٠٪ طبيعية — بدون أي مواد كيميائية',
    subServices: [
      {
        id: 'nt1',
        nameAr: 'عناية بشرة طبيعية',
        nameEn: 'Organic Facial',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'منتجات عضوية معتمدة',
      },
      {
        id: 'nt2',
        nameAr: 'صبغات شعر طبيعية',
        nameEn: 'Natural Hair Dye',
        price: 300,
        durationMin: 90,
        emoji: '',
        precautions: 'حناء وأعشاب طبيعية',
      },
      {
        id: 'nt3',
        nameAr: 'قناع وجه طبيعي',
        nameEn: 'Natural Face Mask',
        price: 120,
        durationMin: 25,
        emoji: '',
        precautions: 'مكونات طازجة',
      },
      {
        id: 'nt4',
        nameAr: 'زيوت عطرية',
        nameEn: 'Essential Oil Therapy',
        price: 180,
        durationMin: 40,
        emoji: '',
        precautions: 'زيوت نقية ١٠٠٪',
      },
    ],
  },
  luxury_spa: {
    nameAr: 'يوم سبا فاخر',
    nameEn: 'Luxury Spa Day',
    emoji: '',
    description: 'تجربة سبا فاخرة — يوم كامل من التدليل والرفاهية',
    subServices: [
      {
        id: 'lx1',
        nameAr: 'يوم سبا ملكي',
        nameEn: 'Royal Spa Day',
        price: 2500,
        durationMin: 360,
        emoji: '',
        precautions: 'باقة كاملة ٦ ساعات',
      },
      {
        id: 'lx2',
        nameAr: 'نصف يوم سبا',
        nameEn: 'Half-Day Spa',
        price: 1200,
        durationMin: 180,
        emoji: '',
        precautions: 'مساج + عناية + غداء',
      },
      {
        id: 'lx3',
        nameAr: 'سبا مسائي',
        nameEn: 'Evening Spa',
        price: 800,
        durationMin: 120,
        emoji: '',
        precautions: 'مساج + عشاء خفيف',
      },
    ],
  },
  homemaker_beauty: {
    nameAr: 'عناية ربات البيوت',
    nameEn: 'Homemaker Beauty',
    emoji: '',
    description: 'باقات عناية تناسب جدول ربة المنزل — سريعة وفعالة',
    subServices: [
      {
        id: 'hm1',
        nameAr: 'باقة ربة المنزل',
        nameEn: 'Homemaker Package',
        price: 350,
        durationMin: 90,
        emoji: '',
        precautions: 'شعر + أظافر + بشرة',
      },
      {
        id: 'hm2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Hand Care Treatment',
        price: 120,
        durationMin: 30,
        emoji: '',
        precautions: 'للأيدي المتعبة من العمل',
      },
      {
        id: 'hm3',
        nameAr: 'استرخاء منزلي',
        nameEn: 'At-Home Relaxation',
        price: 400,
        durationMin: 120,
        emoji: '️',
        precautions: 'زيارة منزلية',
      },
    ],
  },
  cancer_survivor: {
    nameAr: 'عناية المتعافيات',
    nameEn: 'Cancer Survivor Beauty',
    emoji: '️',
    description: 'خدمات تجميل لطيفة للمتعافيات من السرطان — عناية بكل حب',
    subServices: [
      {
        id: 'cv1',
        nameAr: 'عناية بشرة لطيفة',
        nameEn: 'Ultra-Gentle Facial',
        price: 220,
        durationMin: 40,
        emoji: '',
        precautions: 'منتجات خالية من المهيجات',
      },
      {
        id: 'cv2',
        nameAr: 'تصفيف شعر لطيف',
        nameEn: 'Gentle Hair Styling',
        price: 180,
        durationMin: 35,
        emoji: '‍️',
        precautions: 'للشعر الخفيف',
      },
      {
        id: 'cv3',
        nameAr: 'جلسة دعم نفسي',
        nameEn: 'Beauty Support Session',
        price: 200,
        durationMin: 50,
        emoji: '',
        precautions: 'دعم وتشجيع',
      },
    ],
  },
  single_mother: {
    nameAr: 'عناية الأم العزباء',
    nameEn: 'Single Mother Beauty',
    emoji: '',
    description: 'خدمات سريعة وبأسعار مناسبة للأمهات العازبات — أنتِ تستحقين',
    subServices: [
      {
        id: 'sm1',
        nameAr: 'باقة الأم العزباء',
        nameEn: 'Single Mom Package',
        price: 250,
        durationMin: 75,
        emoji: '',
        precautions: 'شعر + بشرة + أظافر',
      },
      {
        id: 'sm2',
        nameAr: 'خدمة مسائية',
        nameEn: 'Evening Service',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'بعد نوم الأطفال',
      },
      {
        id: 'sm3',
        nameAr: 'جلسة استرخاء سريعة',
        nameEn: 'Quick Relaxation',
        price: 100,
        durationMin: 25,
        emoji: '',
        precautions: 'استراحة أمومة',
      },
    ],
  },
  accessible_beauty: {
    nameAr: 'عناية ذوات الاحتياجات',
    nameEn: 'Accessible Beauty',
    emoji: '',
    description: 'خدمات تجميل مهيأة لذوات الاحتياجات الخاصة — وصول سهل وراحة تامة',
    subServices: [
      {
        id: 'ab1',
        nameAr: 'جلسة عناية مهيأة',
        nameEn: 'Accessible Beauty Session',
        price: 250,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'مداخل واسعة وكراسي متحركة',
      },
      {
        id: 'ab2',
        nameAr: 'خدمة منزلية',
        nameEn: 'Home Visit Service',
        price: 350,
        durationMin: 90,
        emoji: '',
        precautions: 'الفنية تأتي إليكِ',
      },
      {
        id: 'ab3',
        nameAr: 'استشارة عناية',
        nameEn: 'Beauty Consultation',
        price: 100,
        durationMin: 30,
        emoji: '',
        precautions: 'منتجات مناسبة لاحتياجاتكِ',
      },
    ],
  },
  diabetic_care: {
    nameAr: 'عناية مريضات السكر',
    nameEn: 'Diabetic-Safe Beauty',
    emoji: '',
    description: 'خدمات آمنة لمريضات السكري — عناية بالأقدام والبشرة الحساسة',
    subServices: [
      {
        id: 'db1',
        nameAr: 'باديكير آمن',
        nameEn: 'Diabetic-Safe Pedicure',
        price: 200,
        durationMin: 45,
        emoji: '',
        precautions: 'تعقيم طبي وتعامل لطيف',
      },
      {
        id: 'db2',
        nameAr: 'عناية بالأقدام',
        nameEn: 'Foot Care Treatment',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'ترطيب مكثف بدون جروح',
      },
      {
        id: 'db3',
        nameAr: 'عناية بشرة لطيفة',
        nameEn: 'Gentle Skincare',
        price: 180,
        durationMin: 40,
        emoji: '',
        precautions: 'منتجات طبية آمنة',
      },
    ],
  },
  healthcare_worker: {
    nameAr: 'عناية الكوادر الصحية',
    nameEn: 'Healthcare Worker Beauty',
    emoji: '🩺',
    description: 'خدمات مخصصة للطبيبات والممرضات — بعد مناوبات طويلة',
    subServices: [
      {
        id: 'hw1',
        nameAr: 'مساج ظهر وأكتاف',
        nameEn: 'Back & Shoulder Massage',
        price: 200,
        durationMin: 40,
        emoji: '‍️',
        precautions: 'لتخفيف آلام الوقوف الطويل',
      },
      {
        id: 'hw2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Healthcare Hand Care',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'للأيدي المتعبة من الغسيل المتكرر',
      },
      {
        id: 'hw3',
        nameAr: 'جلسة عناية سريعة',
        nameEn: 'Quick Recovery Session',
        price: 180,
        durationMin: 35,
        emoji: '',
        precautions: 'قبل أو بعد المناوبة',
      },
    ],
  },
  teacher_beauty: {
    nameAr: 'عناية المعلمات',
    nameEn: 'Teacher Beauty',
    emoji: '',
    description: 'خدمات تناسب جدول المعلمات — بعد الدوام المدرسي وفي العطل',
    subServices: [
      {
        id: 'tc1',
        nameAr: 'باقة المعلمة',
        nameEn: 'Teacher Package',
        price: 300,
        durationMin: 90,
        emoji: '',
        precautions: 'شعر + بشرة + أظافر',
      },
      {
        id: 'tc2',
        nameAr: 'عناية بالصوت والحنجرة',
        nameEn: 'Voice & Throat Care',
        price: 120,
        durationMin: 30,
        emoji: '️',
        precautions: 'مساج واسترخاء',
      },
      {
        id: 'tc3',
        nameAr: 'إطلالة اليوم الدراسي',
        nameEn: 'School Day Look',
        price: 150,
        durationMin: 40,
        emoji: '',
        precautions: 'مكياج طبيعي خفيف',
      },
    ],
  },
  entrepreneur_beauty: {
    nameAr: 'عناية رائدات الأعمال',
    nameEn: 'Entrepreneur Woman Beauty',
    emoji: '',
    description: 'إطلالات قوية للمرأة القيادية — مظهر يعكس نجاحكِ',
    subServices: [
      {
        id: 'ep1',
        nameAr: 'إطلالة سيدات الأعمال',
        nameEn: 'Power Look Package',
        price: 500,
        durationMin: 120,
        emoji: '‍',
        precautions: 'مكياج + شعر + استشارة',
      },
      {
        id: 'ep2',
        nameAr: 'إطلالة اجتماعات',
        nameEn: 'Meeting Ready Look',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'إطلالة احترافية',
      },
      {
        id: 'ep3',
        nameAr: 'باقة السفر',
        nameEn: 'Business Travel Package',
        price: 400,
        durationMin: 90,
        emoji: '️',
        precautions: 'إطلالة تدوم طوال اليوم',
      },
    ],
  },
  night_shift_beauty: {
    nameAr: 'عناية الليليات',
    nameEn: 'Night Shift Beauty',
    emoji: '',
    description: 'خدمات تناسب العاملات ليلاً — مواعيد صباحية ومسائية مرنة',
    subServices: [
      {
        id: 'ns1',
        nameAr: 'عناية بعد الدوام',
        nameEn: 'Post-Shift Recovery',
        price: 250,
        durationMin: 60,
        emoji: '‍️',
        precautions: 'للاسترخاء بعد ليلة عمل',
      },
      {
        id: 'ns2',
        nameAr: 'علاج الهالات',
        nameEn: 'Dark Circle Treatment',
        price: 180,
        durationMin: 30,
        emoji: '️',
        precautions: 'لإخفاء آثار السهر',
      },
      {
        id: 'ns3',
        nameAr: 'باقة ليلية',
        nameEn: 'Night Worker Bundle',
        price: 350,
        durationMin: 100,
        emoji: '',
        precautions: 'مساج + بشرة + استرخاء',
      },
    ],
  },
  grandmother_beauty: {
    nameAr: 'عناية الجدات',
    nameEn: 'Grandmother Beauty (60+)',
    emoji: '',
    description: 'عناية لطيفة وراقية للأمهات الكبيرات — لأن الجمال ليس له عمر',
    subServices: [
      {
        id: 'gm1',
        nameAr: 'باقة الجدة',
        nameEn: 'Grandmother Package',
        price: 350,
        durationMin: 100,
        emoji: '',
        precautions: 'شعر + بشرة + أظافر',
      },
      {
        id: 'gm2',
        nameAr: 'عناية بالبشرة الناضجة',
        nameEn: 'Senior Skincare',
        price: 250,
        durationMin: 50,
        emoji: '',
        precautions: 'ترطيب عميق',
      },
      {
        id: 'gm3',
        nameAr: 'جلسة مع الحفيدة',
        nameEn: 'Grandma-Granddaughter',
        price: 500,
        durationMin: 150,
        emoji: '‍',
        precautions: 'جلسة مشتركة مميزة',
      },
    ],
  },
  mother_of_bride: {
    nameAr: 'عناية أم العروس',
    nameEn: 'Mother of the Bride',
    emoji: '‍',
    description: 'إطلالة مميزة لأم العروس في يوم الزفاف — أنتِ نجمة أيضاً',
    subServices: [
      {
        id: 'mb1',
        nameAr: 'إطلالة أم العروس',
        nameEn: 'MOB Complete Look',
        price: 600,
        durationMin: 150,
        emoji: '',
        precautions: 'مكياج + شعر + بشرة',
      },
      {
        id: 'mb2',
        nameAr: 'باقة أم العروس',
        nameEn: 'MOB Package',
        price: 1200,
        durationMin: 250,
        emoji: '',
        precautions: '٣ جلسات قبل الزفاف',
      },
      {
        id: 'mb3',
        nameAr: 'تجربة مكياج',
        nameEn: 'MOB Makeup Trial',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'جلسة تجربة',
      },
    ],
  },
  baby_shower: {
    nameAr: 'عناية الحامل قبل الولادة',
    nameEn: 'Baby Shower Beauty',
    emoji: '',
    description: 'إطلالة متألقة لحفل استقبال المولود — احتفلي بقرب وصول طفلكِ',
    subServices: [
      {
        id: 'bs1',
        nameAr: 'إطلالة بيبي شاور',
        nameEn: 'Baby Shower Look',
        price: 300,
        durationMin: 90,
        emoji: '',
        precautions: 'مكياج + شعر',
      },
      {
        id: 'bs2',
        nameAr: 'باقة الحامل',
        nameEn: 'Mama-to-Be Package',
        price: 450,
        durationMin: 150,
        emoji: '',
        precautions: 'مساج حمل + عناية + مكياج',
      },
      {
        id: 'bs3',
        nameAr: 'حناء بيبي شاور',
        nameEn: 'Baby Shower Henna',
        price: 200,
        durationMin: 50,
        emoji: '',
        precautions: 'حناء طبيعية آمنة',
      },
    ],
  },
  bridal_party: {
    nameAr: 'وصيفات العروس',
    nameEn: 'Bridal Party Beauty',
    emoji: '‍️',
    description: 'باقات جماعية لوصيفات العروس — إطلالات متناسقة بأفضل الأسعار',
    subServices: [
      {
        id: 'bp1',
        nameAr: 'باقة الوصيفات (٣)',
        nameEn: 'Bridesmaid Trio',
        price: 750,
        durationMin: 180,
        emoji: '',
        precautions: '٣ إطلالات متطابقة',
      },
      {
        id: 'bp2',
        nameAr: 'باقة الوصيفات (٥)',
        nameEn: 'Bridesmaid Group (5)',
        price: 1200,
        durationMin: 300,
        emoji: '',
        precautions: '٥ إطلالات',
      },
      {
        id: 'bp3',
        nameAr: 'إطلالة وصيفة',
        nameEn: 'Single Bridesmaid',
        price: 280,
        durationMin: 60,
        emoji: '',
        precautions: 'إطلالة فردية',
      },
    ],
  },
  retirement_beauty: {
    nameAr: 'عناية المتقاعدات',
    nameEn: 'Retirement Beauty',
    emoji: '️',
    description: 'باقات عناية للمرأة بعد التقاعد — اكتشفي نفسكِ من جديد',
    subServices: [
      {
        id: 'rt1',
        nameAr: 'باقة التقاعد',
        nameEn: 'Retirement Package',
        price: 600,
        durationMin: 150,
        emoji: '',
        precautions: 'تجديد شامل',
      },
      {
        id: 'rt2',
        nameAr: 'استشارة نمط حياة',
        nameEn: 'Lifestyle Consultation',
        price: 250,
        durationMin: 60,
        emoji: '',
        precautions: 'روتين جديد',
      },
      {
        id: 'rt3',
        nameAr: 'جلسة استرخاء',
        nameEn: 'Retirement Relaxation',
        price: 350,
        durationMin: 90,
        emoji: '‍️',
        precautions: 'يوم تدليل',
      },
    ],
  },
  expat_beauty: {
    nameAr: 'عناية الوافدات',
    nameEn: 'Expat Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل ترحيبية للوافدات إلى المملكة — أهلاً بكِ',
    subServices: [
      {
        id: 'ex1',
        nameAr: 'باقة الترحيب',
        nameEn: 'Welcome Package',
        price: 400,
        durationMin: 120,
        emoji: '',
        precautions: 'تعريف بالمنتجات المحلية',
      },
      {
        id: 'ex2',
        nameAr: 'استشارة مناخية',
        nameEn: 'Climate Adaptation',
        price: 200,
        durationMin: 45,
        emoji: '️',
        precautions: 'عناية مناسبة للمناخ',
      },
      {
        id: 'ex3',
        nameAr: 'إطلالة سعودية',
        nameEn: 'Saudi Look',
        price: 300,
        durationMin: 60,
        emoji: '',
        precautions: 'مكياج خليجي',
      },
    ],
  },
  police_firefighter: {
    nameAr: 'عناية البطلات',
    nameEn: 'Women in Uniform Beauty',
    emoji: '‍️',
    description: 'خدمات عناية للعاملات في المجالات العسكرية والأمنية — أنتن بطلات',
    subServices: [
      {
        id: 'pf1',
        nameAr: 'مساج عضلي',
        nameEn: 'Deep Muscle Recovery',
        price: 280,
        durationMin: 60,
        emoji: '',
        precautions: 'للاسترخاء بعد المهام',
      },
      {
        id: 'pf2',
        nameAr: 'عناية سريعة',
        nameEn: 'Quick Beauty Refresh',
        price: 150,
        durationMin: 30,
        emoji: '',
        precautions: 'قبل أو بعد الدوام',
      },
      {
        id: 'pf3',
        nameAr: 'باقة البطلة',
        nameEn: 'Hero Package',
        price: 450,
        durationMin: 120,
        emoji: '️',
        precautions: 'مساج + بشرة + شعر',
      },
    ],
  },
  journalist_beauty: {
    nameAr: 'عناية الإعلاميات',
    nameEn: 'Media Woman Beauty',
    emoji: '',
    description: 'إطلالات جاهزة للكاميرا — للصحفيات والمذيعات والمؤثرات',
    subServices: [
      {
        id: 'jr1',
        nameAr: 'مكياج كاميرا',
        nameEn: 'Camera-Ready Makeup',
        price: 350,
        durationMin: 60,
        emoji: '',
        precautions: 'يدوم تحت الأضواء',
      },
      {
        id: 'jr2',
        nameAr: 'إطلالة مقابلة',
        nameEn: 'Interview Look',
        price: 250,
        durationMin: 50,
        emoji: '️',
        precautions: 'طبيعي واحترافي',
      },
      {
        id: 'jr3',
        nameAr: 'باقة الظهور الإعلامي',
        nameEn: 'Media Appearance Pack',
        price: 500,
        durationMin: 100,
        emoji: '',
        precautions: 'مكياج + شعر + استشارة',
      },
    ],
  },
  artist_beauty: {
    nameAr: 'عناية الفنانات',
    nameEn: 'Artist Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للفنانات والمبدعات — لأن الإبداع يبدأ من داخلكِ',
    subServices: [
      {
        id: 'ar1',
        nameAr: 'إطلالة افتتاح معرض',
        nameEn: 'Gallery Opening Look',
        price: 350,
        durationMin: 60,
        emoji: '️',
        precautions: 'إطلالة فنية مميزة',
      },
      {
        id: 'ar2',
        nameAr: 'عناية بالأيدي',
        nameEn: 'Artist Hand Care',
        price: 180,
        durationMin: 35,
        emoji: '',
        precautions: 'للرسامات والنحاتات',
      },
      {
        id: 'ar3',
        nameAr: 'جلسة إلهام',
        nameEn: 'Inspiration Session',
        price: 250,
        durationMin: 80,
        emoji: '',
        precautions: 'مساج + تأمل + إبداع',
      },
    ],
  },
  tech_woman: {
    nameAr: 'عناية التقنيات',
    nameEn: 'Tech Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل للمبرمجات والمهندسات — لأن التقنية والجمال معاً',
    subServices: [
      {
        id: 'tw1',
        nameAr: 'عناية بالعينين',
        nameEn: 'Screen-Time Eye Care',
        price: 200,
        durationMin: 35,
        emoji: '️',
        precautions: 'لتخفيف إجهاد الشاشات',
      },
      {
        id: 'tw2',
        nameAr: 'مساج رقبة وأكتاف',
        nameEn: 'Tech Neck Massage',
        price: 220,
        durationMin: 40,
        emoji: '‍️',
        precautions: 'لتخفيف آلام الجلوس',
      },
      {
        id: 'tw3',
        nameAr: 'مانيكير تقنية',
        nameEn: 'Techie Manicure',
        price: 130,
        durationMin: 30,
        emoji: '',
        precautions: 'أظافر قصيرة وعملية',
      },
    ],
  },
  nomad_beauty: {
    nameAr: 'جمال البدويات',
    nameEn: 'Bedouin Woman Beauty',
    emoji: '',
    description: 'خدمات تجميل تقليدية مستوحاة من تراث البادية — أصالة وجمال',
    subServices: [
      {
        id: 'nd1',
        nameAr: 'حناء بدوية',
        nameEn: 'Bedouin Henna',
        price: 250,
        durationMin: 60,
        emoji: '',
        precautions: 'نقوش تقليدية أصيلة',
      },
      {
        id: 'nd2',
        nameAr: 'خلطات بدوية',
        nameEn: 'Bedouin Herbal Mix',
        price: 200,
        durationMin: 50,
        emoji: '',
        precautions: 'أعشاب صحراوية',
      },
      {
        id: 'nd3',
        nameAr: 'إطلالة بدوية',
        nameEn: 'Bedouin Look',
        price: 300,
        durationMin: 75,
        emoji: '️',
        precautions: 'مكياج + حناء + عطور',
      },
    ],
  },
};
